-- MySQL Schema for Guia de Parceiros (formerly ISTAA)

CREATE DATABASE IF NOT EXISTS guia_parceiros CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE guia_parceiros;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('superadmin', 'editor', 'viewer') NOT NULL DEFAULT 'viewer',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tags (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  category VARCHAR(100) NOT NULL,
  color VARCHAR(20) DEFAULT '#3b82f6'
);

CREATE TABLE IF NOT EXISTS organizations (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  site VARCHAR(255),
  status ENUM('Ativo', 'Inativo', 'Em análise') NOT NULL DEFAULT 'Em análise',
  logo_url TEXT,
  description TEXT,
  country VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contacts (
  id VARCHAR(36) PRIMARY KEY,
  org_id VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(50),
  role VARCHAR(100),
  FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS organization_tags (
  org_id VARCHAR(36) NOT NULL,
  tag_id VARCHAR(36) NOT NULL,
  PRIMARY KEY (org_id, tag_id),
  FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

-- Insert a default superadmin user (password: Admin@123)
-- The hash is generated by bcrypt for 'Admin@123'
INSERT IGNORE INTO users (id, email, password_hash, role) 
VALUES (UUID(), 'paulo.cardoso@maiscorporativo.tur.br', '$2b$10$wN9P358J.9Q/2x4Q/rU8uuzrV5QhXlZ.k9xR.tQ4H1yE8T8b/gR3G', 'superadmin');
